### ISSUE TITLE
Very slow scrolling if "Deep zooming images" is enabled

### ISSUE THREAD

**Issue by linux019** [SimpleMobileTools/Simple-Gallery#1348]
I have  a 8-core cpu phone with 4Gb RAM and scrolling between images works well without this option enabled. But image quality is very poor even if I try to zoom in/out any images. It seems you need to use https://developer.android.com/guide/topics/graphics/hardware-accel to speed up image upscaling or downscaling

**Comment by devbazilio** [comment]
Please see.
1st app is Google photos - it works very fast and zooms in/out well with original quality
2nd is Simple gallery
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/UjUs69Oa-fg/0.jpg)](UjUs69Oa-fg)

**Comment by tibbi** [comment]
do you have the "Show images in the highest possible quality" disabled in the app settings? It is at the "Deep zoomable images section".

**Comment by devbazilio** [comment]
It works a bit faster if this option is unchecked, but also very slow. I can take a video with unchecked "highest quality".
Thanks 

На 24 марта 2019 г., 13:07, в 13:07, Tibor Kaputa <notifications@github.com> написал:п>do you have the "Show images in the highest possible quality" disabled

**Comment by tibbi** [comment]
no need. Some improvements are obviously wanted, it just isnt that easy to achieve. Thanks

**Comment by NotSoImportant** [comment]
I experiance the same stuttering on my Motorola G4 Plus.
This also happens in Signal as described here: https://github.com/signalapp/Signal-Android/issues/7208#issuecomment-787108195. - they tend to think it is because of a low memclass.
Zooming however works smooth in other apps, e.g. ghost commander: https://sourceforge.net/projects/ghostcommander/
Maybe you can have a look into their implementation?

**Comment by NotSoImportant** [comment]
This issue can be closed
