### ISSUE TITLE
Some hidden folders are still showing up

### ISSUE THREAD

**Issue by seffparker** [SimpleMobileTools/Simple-Gallery#1409]
I have a strange issue. Some hidden folders are still visible whatever the settings are.
My sample folder tree:

`-/sdcard/-|`
`..........|-Downloads/`
`.....................|-`.nomedia
`.....................|-.image1.jpg`
`..........|-Photos/`
`..................|-`.nomedia
`..................|-Family/`
`..........................|-.nomedia`
`..........................|-image2.jpg`

**Excluded folders:** /sdcard/
**Included folders:** /sdcard/Downloads/, /sdcard/Photos
**Hidden folder**:  /sdcard/Downloads/, /sdcard/Photos, /sdcard/Photos/Family

Now, the folder Downloads is always visible, even if I hide it. The folder Family is only visible after I enter the password to show hidden folders. Not sure whats wrong with some folders. Not only the Downloads/ folder, it affect other folders too in the root dir and sub folders too.

When I press-and-hold the Downloads/ folder, the menu shows _"Unihide folder"_, even it is already showing.

Tried the following:
- Reset app data and configured from scratch
- Cleared system media database and ran media scanner again

Device Info:
- POCO F1 10.3.4
- Android 9
- SimpleGallery Pro 6.7.0 (Valid Purchase from PlayStore)

**Comment by seffparker** [comment]
Got some additional info.

If we inlcude a directory /sdcard/level1/level2/level_N/ , then the direct child contents of level_N/ will be always visible regardless of the .nomedia file.

that's a bug.

**Comment by tibbi** [comment]
thats not a bug, it is intentional since both inclusion and .nomedia are recursive and affect subfolders too. I picked the inclusion to have a higher priority.

**Comment by seffparker** [comment]
No problem. Any method to hide (include with password) a direct child folder in /sdcard without including the entire /sdcard?

**Comment by tibbi** [comment]
the most specific rule has always the highest priority. Im confused by your complicated way of managing folder visibility already, but if you include the whole SD card and exclude a specific subfolder, it will be excluded and not visible.

**Comment by seffparker** [comment]
If an included folder had a .nomedia, it should be hidden. And make it visible only after entering the password.

What do you think?

**Comment by tibbi** [comment]
included folders are visible with .nomedia too. If you want to hide them, prefix their name with a dot. Anyway I see that it works fine, you just didnt know how exactly should it behave.

**Comment by seffparker** [comment]
May be I don't know. I just moved to SimpleGallery from QuickPic. 

QuickPic had no behaviour like these.

All subfolders of a hidden folder is hidden. Any folder with a .nomedia is hidden.

Not sure what your algorithm does.

**Comment by MacGyverNL** [comment]
> the most specific rule has always the highest priority. Im confused by your complicated way of managing folder visibility already, but if you include the whole SD card and exclude a specific subfolder, it will be excluded and not visible.

Either this is an inaccurate description of what you want to happen, or there's a bug. Simple usecase: I'm using git-annex to sync my media folders. Folder structure is
```
SDCard
...
|- annexfolder (included)
... |- .git           (excluded)
    |    |- annex
    |    |       |- objects
    |   ...     ...     |- lots and lots of backing objects with hashed filenames
    |
    |- 100ANDRO
    |- Filesync
```
I've ensured there's no .nomedia in the path leading up to the annexfolder. The only rules set are those next to the folder names. Even though the excluded rule is more specific (i.e. on the lower .git folder), all the media files in its objects subfolders show up. I believe this may be unintended behaviour.

**Comment by tibbi** [comment]
ye recursive inclusion is checked first. Anyway here are the rules https://github.com/SimpleMobileTools/Simple-Gallery/blob/96a4da2bf3d6b2b1be4a6bb5f2099fa04f34c18e/app/src/main/kotlin/com/simplemobiletools/gallery/pro/extensions/String.kt#L20 , you can check it out. The rules work just fine in 99% of cases, such advanced folder including/excluding isnt really the intended behaviour.

**Comment by MacGyverNL** [comment]
I honestly think that "most specific directive recurses" is actually the least "advanced" behaviour, in that it makes the most sense to people (judging by the amount of bug reports exclusion sees). The current confusion probably stems from the fact that exclusion usually recurses *up to* an inclusion directive, but never *below* an inclusion directive.

It could be changed into a use of `maxBy` with a selector that yields `it.length` if `startsWith` is true and 0 otherwise, and then use length comparison instead of the fallthrough. But I understand if you think that's too inefficient.

I also thought that changing this might be surprising to people not using hierarchical grouped view in included folders and suddenly seeing huge swathes of folders disappear if they exclude what happens to be a top-level folder -- but then I realized that's what now *already happens* if they're not working in a folder that has an inclusion directive.

**Comment by MacGyverNL** [comment]
Well, as it turns out, I didn't actually need the inclusion directives anyway -- I added them because Simple-Gallery appeared not to be detecting media very deep in the SDcard hierarchy. It turns out it's likely that that was simply a matter of having to scan so many folders, because when I removed them and rebooted everything stayed in place, so I can just rely on the recursion behaviour without include directives.

**Comment by seffparker** [comment]
>I dont plan changing it now in any way.
Let it be. But, can you please add an option to chose the in/exclusion priority (i.e., which is processed first) for users within app, rather than hardcoding in the codes?

This way, we can make the app more flexible.

Currently, this app has no way of adding a protected folder only, without including its parent and its all other children.

Including the whole sdcard/ makes a lot of unnecessary folders to be included automatically and we have to exclude each every of them individually. And any newly created folders are again added automatically. 

An optional priority selection would be a great idea.
