### ISSUE TITLE
When editing photos from Simple Gallery in Google Photos editor, new photos are invisible until media is rescanned

### ISSUE THREAD

**Issue by nyanpasu64** [SimpleMobileTools/Simple-Gallery#1538]
- In Simple Gallery, click the Edit button on a picture (mine are located in /sdcard/Download). Pick Google Photos editor, optionally edit, and click "Save copy".
- Open Discord app, and either open or swipe-to-refresh the "attach a photo" panel. The edited picture will not appear.
- Open Google Photos and go to the album containing the original and edited picture. Google Photos will rescan the folder and find the new file. Now it will appear in Discord.

On the other hand, creating a new photo via Simple Gallery's editor (which asks for a file path) are discovered immediately in Discord. When I trash a photo in Simple Gallery, it disappears immediately from Discord.

Simple Gallery 6.9.1, Google Photos 4.21.0.259804562 (very long number).

**Comment by tibbi** [comment]
Not sure what is the issue there. Are you sure it is a Simple Gallery related one?

**Comment by jimbo1qaz** [comment]
The bug is that images created by the Google Photos editor are visible in other Android apps, only when invoked by Google Photos, and not vy Simple Gallery.

Also, Discord is not the important part of the bug report, but merely a way of viewing Android's media cache. If you follow the procedure I stated, Telegram also does not see the files, and likely USB MTP doesn't know their existence either (though I didn't check on PC).

**Comment by ForgottenUmbrella** [comment]
Sounds like Google Photos' editor isn't updating the MediaStore/initiating the MediaScanner, but rather is offloading that responsibility to the main Google Photos activity (Simple Gallery's editor, on the other hand, *is* being a good citizen, as evident in the Discord example). This would be an issue with Google Photos.

**Comment by skjnldsv** [comment]
Same issue here. This is definitely a missing query to Android's MediaLibrary API.
