### ISSUE TITLE
Sort by date taken broken

### ISSUE THREAD

**Issue by P1M0N** [SimpleMobileTools/Simple-Gallery#157]
Since the last update sorting by date taken seems to be broken. Instead of the Exit data, the date when the picture was modified the last time is used for sorting.

Steps to reproduce:
- Copy pictures from internal to external memory using any Android file manager (Android will override the last  modified date) 
- Open Simple Gallery and select "sort by date taken"
- There's no difference to "sort by date modified" 
- The pictures are sorted by the date last modified (kind of randomly since the date is the same for all)

**Comment by jerryn70** [comment]
I'm also facing this issue

**Comment by tibbi** [comment]
ye it is broken, under the hood its using the Last Modified value. I want to fix it, I just still couldnt find any way how to do it without drastically decreasing the performance :/

**Comment by jerryn70** [comment]
Again sort by date is broken

**Comment by ramack** [comment]
mh, since I moved all pictures to a different location - which broke the file creation date (see #310) my pictures are sorted by random instead of date. For sure reading EXIF can dramatically impact performance, though it would be great to have an option to fix the file modification date by exif - afterwards the file date would again give the good order.

**Comment by tibbi** [comment]
ye I will get back to it someday. I dont like the current solution either, but it really isnt simple to get everything right.

**Comment by utack** [comment]
Seems broken again on the latest version  :(

**Comment by tibbi** [comment]
what exactly is broken? What app version are you using?
