### ISSUE TITLE
Feature request: Treat folders as folders

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Gallery#1610]
I very much love the straightforward way simple gallery treats things, so it has become my favourite gallery app. But I miss a feature that I used to have years ago on my Samsung Wave II running Samsungs proprietary OS, Bada. There the gallery had folders that were in fact treated as folders:

You only saw the name of the folder, or images located in there. Images (or sub-folders) would only visible after you entered the folder. Just like Windows or Linux do it.

This would have the beauty that one could arrange the myriads of photos taken and give them some structure. I for instance, like to group photos from on spot I travelled to under a folder bearing the name of the place. When I re-visit the place, I create sub-folders with the year.

But if sub-folders are all treated the same, this leads to many folders with the same name...

Since this would be a significant change in behaviour for users who got used to the current way, I would suggest such a new feature as switchable, with default off.

Optionally, there could be a selectable image from a sub-folder chosen to represent the folder.

Thanks for considering it
hman2

**Comment by tibbi** [comment]
you can already enable "Group direct subfolders" option in Menu -> Change view type in the Pro version.

**Comment by hman2** [comment]
...that's not what I meant. I do not want to manually group some folders, the folder structure is already there, formed by directories on the SD card, but Simple Gallery throws all subfolders into front view, thus negating the existing structure...

**Comment by buttercookie42** [comment]
I'm looking for something like this, too, but while "Group direct subfolders" indeed goes in the right direction, it only seems to get halfway there, because while some folders seem to get grouped correctly underneath e.g. the "SD card" root folder, a lot of subfolders still end up being displayed directly in the root view.

I'm not yet absolutely sure what happens, but my suspicion is that if there are some folder levels without any browseable (for Simple Gallery) content, then any further subfolders deeper down in that part of the directory tree which *do* have some browseable content end up being attached directly to the root overview.
