### ISSUE TITLE
Critical bug: file lost after a move action 

### ISSUE THREAD

**Issue by FabriceSalvaire** [SimpleMobileTools/Simple-Gallery#1650]
**What happened: Some files was lost after a move action.**  ( It could be a concurrent copy was running at the same time by mistake, I don't remember exactly )

* Device is Samsung Galaxy S5 / Android 5
* Source and target was on an external SD card !
* Many popup windows showing errors appeared, Kotlin error etc. android woodoo ...
  ( Also notice these windows cannot be removed and spoil the screen )

**I strongly suggest to check the application code !!!**

* where is done move code ? Android or app code ?
* is there background thread ? lock to prevent concurrent action ?
* can we lost data if something goes wrong ?

**Comment by tibbi** [comment]
it is done in the app. What app version are you using?

**Comment by FabriceSalvaire** [comment]
v6.10.2

**Comment by tibbi** [comment]
try updating to 6.10.5 please, to see if you can still reproduce the issue

**Comment by FabriceSalvaire** [comment]
well, I would stop to use this app to copy/move until I am not sure the code is safe.  I don't see related bugfixes in the newer versions.

Android has this API when the src/target is on the same mount point: https://developer.android.com/reference/java/io/File.html#renameTo(java.io.File) thus it should works without data lost

**Comment by tibbi** [comment]
it works only if they are on the internal storage, even then it has some issues

**Comment by 0rganite** [comment]
Same problem after rotation of a picture on external sd card with v6.10.5.

**Comment by puppykickr** [comment]
I am using this app on two devices with different OS.

The app moves files flawlessly on my 7.1.1, both to and from the SD card and internal memory- and also from internal to internal & SD to SD.

But, the most recent update will not move files on my 8.1.1- between the internal memory and the SD card.

With moving or copying files in this manner, the result is a file correctly named, but with 0b of memory.

The issue began a few updates ago, and waiting a while seemed to solve it.

But now, a 'Gallery - Moving 'file name'  notification appears, and it never completes.

Also, I am using the File Manager app in your app series, and am now having the same problem there as well.

Gallery version - 6.10.6
File Manager version - 6.3.7
(both are from F-Droid)
Device - Poblano VLE 5 
OS - 8.1.1

Once again, both apps work flawlessly on my 7.1.1
This issue only appears with my 8.1.1

**Comment by puppykickr** [comment]
OK.

After extensive testing with other 'file manager' type apps, I was always getting the same results.

So I tried downloading something directly to the SD card, and got the same results again-  'title' 0b.

So now I am blaming the device, not the apps.

I did find a workaround, however.

Perhaps this can help @FabriceSalvaire 

When I restart the device, the files show up on the SD card.

So they are getting moved/copied, but for some reason the device/app is not updating the information unless the device is restarted.

**Comment by tibbi** [comment]
that is the biggest issue with Android, especially file handling :/ There are so many things done differently per device/manufacturer that it really hard to make it work reliable everywhere, if possible at all. Instead of making things easier, Google actually complicates it with every single new release. There is a major change coming soon, possibly the biggest ever starting with Android 10 devices. It will be forced on every app once Android R gets released by the end of 2020, or so. It will cause massive issues to every app relying on browsing devices files.

**Comment by OmlineEditor** [comment]
I confirm that there is a problem. I had problems that the file becomes the size of 0 bytes and it is empty. Sometimes the problem appears spontaneously and I can not repeat it. Once there was a problem that I just leafed quickly files and watched different folders in search of the desired photo. And then the last file in the folder disappeared, the karinka on the folder became gray. I look and see that the file size is zero.

I think the problem is that the files are open not to **_read_**, but on **_reading + recording_** and at this moment there is a problem. Please replace operations on safer, read-only **_reads_** if it is not necessary for operations with files.

Xiaomi Redmi Note 7
Andriod 9.0
Galery 6.20.1 f-droid

**Comment by atonn** [comment]
Also experienced all images/videos lost after a bulk "move" action on a Oneplus 3 with LineageOS. Happened twice this week, so now that I know I just won't use the move function again. I know that it's difficult to support all devices, but the "move" function should possibly show some big fat warning popup on use, with some don't show again checkbox. cheers

**Comment by puppykickr** [comment]
I have the issue of files showing 0 bytes of data, and being unable to be
opened, on my 8.1.0.

This occurs most often with videos, not pictures, and is usually limited to
when I move files from internal to SD card memory.

The workaround is to restart the device.

This has always eecovered the files so far for me.

   (puppykicker)

**Comment by tibbi** [comment]
shouldnt happen anymore after 6.23.0

**Comment by ivanfr90** [comment]
I recently experienced the same problem described using a old version of SimpleGallery. 
The process I followed was:
1º) I selected all photos and videos I wanted to move
2º) Later, I selected the move action and i created a new folder for the destination
3º) Files remain selected without apparently moving to the new location
4º) I reattempted the operation but it said "Overwrite files on destination"? I was confused for this action, so I thougt that first time didn't works well, so selected YES.
5º) After that 5 GB of photos and videos disapperated....

There are any way to recover this files knowing the bug that old versions suffer? 
I'm not using a rooted device, so to create a raw image of the /userdata partition using dd could not be possible... Any suggestions???
