### ISSUE TITLE
Delete the folder itself at deleting its content from the main screen

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1668]
Currently if a folder is deleted from the main screen, only the content is deleted. The folder itself stays, even if "Delete empty folders after deleting their content" is enabled.

**Comment by LuisMBarrera** [comment]
Hello, I'm new at contributing to open-source projects, and I wanted to know if I could help with this issue.

**Comment by tibbi** [comment]
sure, you can take a look at it

**Comment by LuisMBarrera** [comment]
Hey, while checking the code I found these command lines:

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

These wouldn't let me start the project because of the missing file and the actual keystore.
Do you think this needs to be on the development environment? Wouldn't it be convenient to have it only on the release configurations?

**Comment by tibbi** [comment]
ye, I will add some checks there soon, to make it not required for debug builds

**Comment by LuisMBarrera** [comment]
Hey, so I've been trying to replicate the bug and I couldn't. Is it specific to a version or device? Or could you show the bug in action?

**Comment by tibbi** [comment]
added it already

**Comment by puppykickr** [comment]
Just a heads up, this issue is not occurring on my device.

device
ZTE 558VL
os
7.1.1
version
6.10.6

Sometimes it appears that it is occurring, but when I swipe down from the top on the homepage it is fixed.

**Comment by LuisMBarrera** [comment]
Hello, actually my attention shifted to another project due to priorities, so I'm not going to continue with this issue. Thanks for answering my questions and hopefully this issue is resolved soon.
