### ISSUE TITLE
F-Droid NoSourceSince

### ISSUE THREAD

**Issue by piu130** [SimpleMobileTools/Simple-Gallery#1706]
F-Droid marked your app with `This app has features you may not like: NoSourceSince`.
Do you know why and how to fix this? :)

Is this, because of the license change? Or because of the new photo editor?

Latest release was 6.10.8 on F-Droid.

[F-Droid Link](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/).

**Comment by darhma** [comment]
@piu130 
I think it is due to the photo editor that is not open source so either a fully open source version for f-droid is maintained or updates will no longer be available

**Comment by tibbi** [comment]
ye, it is caused by the editor, which is not open source

**Comment by darhma** [comment]
@tibbi 
Are you planning to release a version without photo editor for f-droid?

**Comment by tibbi** [comment]
for now not, we will see later

**Comment by IzzySoft** [comment]
@tibbi how does closed source comply with GPL? Don't you have license issues that way? What license is the photo editor covered by?

**Comment by tibbi** [comment]
I dont see any problems with it, their license is at https://github.com/imgly/pesdk-android-demo/blob/master/LICENSE.md

**Comment by ritzmann** [comment]
"Linking" code under a non-free license into GPL code is trickier than it seems:
https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

My understanding is that you would need to alter the GPL license notice as described in the above link and you would need permission from all 102 contributors (according to Github stats) to Simple Gallery to make that license change.

**Comment by CryptOwl** [comment]
I add my concern that the inclusion of the proprietary library is a very bad decision. Communities  based around free software have been pushing your apps for years. The pretty well known German privacy blogger Mike Kuketz has been recommending your app for quite some time due to its free software nature: https://www.kuketz-blog.de/empfehlungsecke/#android
I have also been recommending Simple Gallery (Pro) in CryptoParty related material (including hundreds of printed handouts) and other of your apps for years. I will be unable to do this since new versions will no longer bee free software and cannot be built in F-Droid. 

Please reconsider this decision.

**Comment by klawdhfzasjhaa** [comment]
Additionally, one could argue that the app ist called Simple Gallery, not "feature rich picture editing app". ;) The basic editing options were sufficiant to me.

**Comment by floppyD** [comment]
Yeah, I don't think the new editor is worth it. The previous one was fine and "Simple" enough.

**Comment by Z3ROGRAV1TYx** [comment]
+1 to this convo, I really don't see the point in having the editor. Also I agree woth CryptOwl on the proprietary library being a bad decision, I praised the app so hard, but since the addition of the editor I just can't anymore. I love the app so much if it wasn't for this. Maybe keep the f-droid one seperate without the editor and keep pushing updates and all?

**Comment by alcoolfire** [comment]
@tibbi: Please reconsider the inclusion of that closed source photo editor library. I'd recently installed this app on multiple phones for multiple people using F-Droid on the basis of it being fully open source. None of these people need the editor functionality, but do need the app to be open source. We'll have to find an alternative app if you cannot maintain an open source version on F-Droid, and that would be a real shame given how good your apps otherwise have been.

**Comment by tibbi** [comment]
version 6.13.0 should be available on f-droid again, without the new editor

**Comment by IzzySoft** [comment]
Great, thanks @tibbi! Did you open an issue with F-Droid to pick up again (or even better, a MR to update Metadata accordingly)? Just asking, because that won't happen automatically until someone triggers it :wink:

**Comment by tibbi** [comment]
@licaon-kter should do it as discussed at https://github.com/SimpleMobileTools/Simple-Gallery/pull/1763

**Comment by IzzySoft** [comment]
A great – if he's already aware of it, it will be done soon™ :smile:

Thanks all who contributed to this!

**Comment by licaon-kter** [comment]
@tibbi I can`t build HEAD, build log says: https://gist.github.com/licaon-kter/be4e07bce781d4024f4554d10305166e
 
`git bisect`:
```
dbaca7aa30551b21d26169b885007ad3e1e0a5b0 is the first bad commit
commit dbaca7aa30551b21d26169b885007ad3e1e0a5b0
Author: tibbi <tibor@kaputa.sk>
Date:   Fri Feb 28 19:58:54 2020 +0100

    make sure the proprietary classes show up in android studio too

:040000 040000 eccfacde6d766df8342f7bb9c7f9c94f64670d41 1e06d529d8ec88ea80e3f91b387b9fd1dbc99c6a M      app
```

**Comment by tibbi** [comment]
I see, it should work with the latest commit. Do I need to create a new release?

**Comment by licaon-kter** [comment]
No need, I'll check now if it builds...

**Comment by tibbi** [comment]
I changed a few more things to avoid changing the app id or version name at the FOSS version

**Comment by licaon-kter** [comment]
@tibbi Thanks, FYI https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6408

**Comment by tibbi** [comment]
cool, thanks
