### ISSUE TITLE
Simple Gallery Pro has no color management

### ISSUE THREAD

**Issue by 86423355844265459587182778** [SimpleMobileTools/Simple-Gallery#1770]
###### SUMMARY
Simple Gallery Pro has no color management, so the app is unable to:
1. Use the embedded profile in images.
2. Use a display profile (monitor profile).

Both points above have to be addressed for more accurate color reproduction.

###### STEPS TO REPRODUCE
Download and open the [test files](https://displaycal.net/icc-color-management-test/ICC_CM_Test.zip). They are created by Florian Höch and released under CC-BY-SA 4.0 license.

###### OBSERVED RESULT
The user will see the same result as in `ICC-Rendering-Intent-Test-expected-result-no-cm.png` and `sRGB_Gray-expected-result-no-cm.png`.
In addition, Simple Gallery Pro provides no setting for using a monitor profile.

###### NOTES
Firefox Nightly (`org.mozilla.fennec_aurora`) on Android has **full** color management, and is able to use a display profile by changing the settings in `about:config`.
(Verification can be done using a profile that swaps the color channel, e.g. `SwappedRedAndGreen.icc`, and you will see that the colors are different after restarting the app.)

You can [profile your tablet or smartphone using DisplayCAL](https://displaycal.net/#display_instrument).

X-Rite's [proprietary app](https://play.google.com/store/apps/details?id=com.xrite.mobiledisplaycalibration) can also be used to profile the smartphone and displaying images, but it only supports limited phone models and their colorimeters.

**Comment by tibbi** [comment]
Actually Im not even sure what this means, looks to be too advanced for a simple file browsing app. Thanks though

**Comment by blitzgneisserin** [comment]
Well actually its very important since most mobile devices have a screen whose color space is considerably larger than srgb. So actually they need color management to display colors correctly. Unfortunately color management does not work properly on android afik. So most devices show oversaturated colors and don't actually use the larger gamut they have.
This is a feature that this app absolutely needs. However I imagine it's not so easy to implement... and I am no dev either.
