### ISSUE TITLE
Option to change filename font size

### ISSUE THREAD

**Issue by ngdias** [SimpleMobileTools/Simple-Gallery#205]
I need to see a caption when I'm browsing the pictures. I'm using the filename, but sometimes the full name doesn't fit in the alloted space. It would be nice to be able to make the font size smaller to fit more characters. Or add a way to save a description into the file in a standard way that can be shown or hidden with a tap, together with the filename and other overlays.

**Comment by tibbi** [comment]
Font size change is unnecessary, what I plan doing is having different modes of displaying the images. Instead of a grid, there will be a simple list similar to https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/screenshots/app_2.png . Its already reported at https://github.com/SimpleMobileTools/Simple-Gallery/issues/42 tho, so Ill close it. If its urgent to you, you can reduce the thumbnails column count to 1 if it makes sense :)

**Comment by ngdias** [comment]
If the filename is for example 'Block building with marble windows.jpg' it is going to be truncated with the current setting. I cannot find a good app that actually overlays a generous amount of text over a full screen image and I find that very frustrating. Small thumbnails with lots of text to the side is really not that useful, as I'm not searching for the photos, I'm learning from them and I need so see them as big as possible and move on to the next one quickly.
Something like what Repost does for reddit images is exactly what I'm looking for. Google photos does something different but usable, but requires an internet connection and uploading images and that just doesn't work for my needs. A setting allowing to adjust the number of filename characters would be a quick way to improve usability for this particular use case.

**Comment by ngdias** [comment]
The text overlay feature could be a good selling point for your app, as I installed quite a few and none is doing it well. AFAIK, it could be an untapped niche.
