### ISSUE TITLE
Tamil language support

### ISSUE THREAD

**Issue by GobinathAL** [SimpleMobileTools/Simple-Gallery#2094]
This app needs to have support for Tamil Language

**Comment by tibbi** [comment]
Translations are done by volunteers, let me know if you want to help translating. The guide for translating is at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . You will need to create 2 files. https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/res/values-ta/strings.xml contains only strings used in the Gallery app, https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values-ta/strings.xml contains strings reused by all apps, so that should be translated too.

**Comment by GobinathAL** [comment]
Ok I will volunteer

**Comment by tibbi** [comment]
ok I created both tamil string files to help you like that, follow the instructions mentioned above for editing files. Thanks
