### ISSUE TITLE
 Show wrong date taken , Please help me answer. 

### ISSUE THREAD

**Issue by hoangchungk53qx1** [SimpleMobileTools/Simple-Gallery#2295]
In your App .  
![image](https://user-images.githubusercontent.com/52132635/145137619-a2121585-0fe0-4537-934c-b6e9dfe37bda.png)
And In your Gallery Default
![image](https://user-images.githubusercontent.com/52132635/145137703-00e4c979-1f19-4644-b7a0-07b42cdb81eb.png)

**Comment by nguyenducanhit** [comment]
I have same issue

**Comment by tibbi** [comment]
if you check the file Properties, does it show the proper date? What app and OS version are you using at all?

**Comment by TwisX** [comment]
The 6.22.2 update caused sorting issues for me as well.

Certain albums have some photos that have a Date Taken value, and some that don't. On previous versions, the Date Modified value would be used as a fallback, so everything was in the correct order even if some photos didn't have a Date Taken value.

With the new update, it throws any photos that don't have a Date Taken value down to the bottom of pile. Sorting by Date Modified "fixes" this since all my photos have a Date Modified value that happens to match the Date Taken values. This doesn't seem ideal though. The old way made a lot of sense.

Not sure if this was an intentional change or a bug.

**Comment by entrapta-dev** [comment]
> The 6.22.2 update caused sorting issues for me as well.
> 
> Certain albums contain some photos that have a Date Taken value, and some that don't. On previous versions, the Date Modified value would be used as a fallback, so everything was in the correct order even if some photos didn't have a Date Taken value.
> 
> With the new update, it throws any photos that don't have a Date Taken value down to the bottom of pile. Sorting by Date Modified "fixes" this since all my photos have a Date Modified value that happens to match the Date Taken values. This doesn't seem ideal though. The old way made a lot of sense.
> 
> Not sure if this was an intentional change or a bug.

Having the same issue. As I edit my photos a lot, even if it's just a simple crop, they get shoved down to "unknown" with their Date Taken completely stripped. Even the edited photos from before this update have no Date Taken and are moved down there. 

Sorting by "Last Modified" does _not_ fix this for me as they are still in the "Unknown" pile on the bottom despite the "Last Modified" date being correct and they should between my other photos as before this update. Adding "Group by Last Modified" in addition o the sorting will correct this but is not ideal as now they are not sorted by Date Taken.

I may be missing something obvious here but this didn't used to be the default behavior.
