### ISSUE TITLE
Does not refresh particular folder.

### ISSUE THREAD

**Issue by usearchbtw** [SimpleMobileTools/Simple-Gallery#2311]
I have found a strange bug in version 5.22.2 in which app does not refresh particular folder after new videos are download.
Manually refreshing by swiping from top to refresh, or clearing App Cache/Data also doesn't show the recently downloaded video nor does uninstalling and reinstalling the app.
However rebooting the phone refreshes the gallery every time. Moving the video file to any other folder (or back to orignal) also makes it show in Gallary.
There is no such problem in version 5.22.1 or earlier.
I use F-Droid version of the app on latest updated Lineage OS 18.1  (Android 11) on Oneplus 6T

**Comment by tibbi** [comment]
Try adding the misbehaving folder in the app Settings - Manage included folders. What app version are you using now? I mean the number in the About section.

**Comment by usearchbtw** [comment]
Sorry, made a mistake app version I'm using is is 6.22.2 and not 5.22.2 and version 6.22.1 or older work fine.

After adding the folder in 'manage included folders' shows the videos but if I download a new video again it doesn't show in the gallery, even though the folder is still in 'manage included folders'. But if I again remove and add it to 'manage included folders' then it shows the newer videos.

**Comment by usearchbtw** [comment]
I mean everytime removing and adding the folder again to 'manage included folders' refreshes it.

**Comment by tibbi** [comment]
isnt it just slow? Some Android 11 related performance improvements are on the roadmap. Try with a folder with less files.

**Comment by usearchbtw** [comment]
No, I don't think it it's slow because when I use app version 6.22.1 pro the same folder refreshes instantly after video is downloaded.

**Comment by tmmkss** [comment]
Same behavior with version 6.22.3 on Android 11 (security update 5.12.2021) for all kinds of images.

- gallery displayes folder with images
- add new image to folder by another app (nextcloud)
- new image is not shown in gallery (default FILES app shows new image without issues)
  - refresh folder in gallery does not help
  - remove parent folder from INCLUDE and INCLUDE parent folder again helps
  - rename image in default FILES app helps - renamed image is shown in gallery
 
Version 6.22.1 works without issues.

**Comment by pebkacs** [comment]
I am experiencing the same thing as tmmkss on Android 12 (Pixel 3).

- When Nextcloud automatically moves a photo to my Nextcloud folder on my phone, the gallery app does not reflect the change.
- Version 6.22.1 works without issues.

Thanks for the great app and all you guys do!

**Comment by Aga-C** [comment]
Are you using SD card? Because when I am trying to reproduce this issue, it happens only with folders on SD card.

**Comment by pebkacs** [comment]
Nope.  No SD card on the Pixel 3.  It does emulate SD card storage going off of the folder names in the file browser, but isn't that pretty standard for Android across the board?

**Comment by Aga-C** [comment]
Ok, actually I can also reproduce it on internal storage, both on real phone and emulator. Seems like some refresh issue for included folders, because it doesn't refresh also when I just move files there.

**Comment by Aga-C** [comment]
I've found out (on Android 12 emulator), that bug was introduced with this commit: https://github.com/SimpleMobileTools/Simple-Gallery/commit/dae13c0261098d2cce050f9e75a0f6a2a492caef. It looks like `getAndroid11FolderMedia` function doesn't fetch all the files. What's strange is that the problem is probably not particularly related to Simple Gallery, but generally to how apps handle files:
- When I move a file from directory to another with Simple File Manager, `getAndroid11FolderMedia` doesn't see this file anymore.
- What's interesting - Google Photos also doesn't see this file, so it looks like Simple File Manager does something wrong while moving files.
- However, all file managers see this file while browsing the folder. However, what I've seen on my phone (OnePlus 9 Pro, Android 11) in built-in file manager file is not visible in Images group, but is visible while browsing a folder.
- When I move the file with the built-in file manager, the file becomes visible both in Simple Gallery and Google Photos.
- I've also noticed a strange behavior on my phone: the file after moving was invisible both in Simple Gallery and in Images group of built-in file manager -however, when I removed the folder from included in Simple Gallery and added it again, the file became visible both in Simple Gallery and Image group of built-in file manager. It looks like it invokes something that makes Android rescan this path for files.

So I assume, there is some issue how apps (Simple File Manager, maybe also NextCloud) handle files. The easiest fix here would be to remove that performance fix for Android 11+ and let Gallery scan folders like it did before - it's more error proof despite being slower.

@tibbi Maybe this change should be reverted, to avoid this problem since it looks like a global issue, not related only to Simple apps?

**Comment by tibbi** [comment]
File Managers work differently, they can access folders like previously. Galleries cannot do that anymore, they have to rely on the mediastore. So some mediastore related operations have to be improved.

**Comment by Silent-Hunter** [comment]
I have noticed this same issue, except it happens if I move or delete any file with a file manager outside of Simple Gallery. When I go back to Simple Gallery, it looks like they're still there, but I can't delete them.

**Comment by tibbi** [comment]
retry with 6.23.0 once it gets, whole file fetching will change on Android 11+
