### ISSUE TITLE
Image shown by using the Camera app preview is incorrect

### ISSUE THREAD

**Issue by wavexx** [SimpleMobileTools/Simple-Gallery#2461]
I frequently have the following problem:

- Take picture using the built-in camera app using the built-in oneplus 6t camera app
- Tap on the preview thumbnail to see the image
- Gallery opens on the wrong (usually previous-to-last) image

If I go back, and tap on the thumbnail image again, the correct image is shown.

Could this be a problem with simple gallery?

**Comment by tibbi** [comment]
if you want a bit longer before opening the captured image, does it work?

**Comment by lipici** [comment]
Yes, it works. 

But its a recent bug, wasnt in last versions.

**Comment by tibbi** [comment]
that is not an issue on our side, it can take a while for the image to be saved properly in the devices MediaStore so that gallery apps are aware of them

**Comment by lipici** [comment]
The problem its from your side. How i said, i use your app and i know. In last versions wasnt like that. Evan if you wait 1 month will still show previous last photo taken foar a few seconds instead to show the last one taken.
    On Saturday, May 28, 2022, 10:16:25 PM GMT+3, Tibor Kaputa ***@***.***> wrote:  
 
 


that is not an issue on our side, it can take a while for the image to be saved properly in the devices MediaStore so that gallery apps are aware of them

**Comment by leaumar** [comment]
@tibbi Just want to chip in as I do believe this should be a simple-gallery bug. I came to report the same problem, though in my case the image that's always wrongly loaded in the first few seconds after taking a new one is the oldest image in the Camera folder, not the second-last.

This not only started happening only recently and independently of e.g. any android update (afaik), it also doesn't happen at all with another gallery app, namely Leafpic Revived (which works normally).

I agree with you the root cause is, if you're right, technical and android's fault, but if another app can do it, surely the poor UX is up to simple-gallery to work around?

**Comment by tibbi** [comment]
leafpic is an abandoned app that hasnt been updated for ages, they dont have to rely on the mediastore at fetching data. They still have access to All files and not just media.

**Comment by leaumar** [comment]
And is that not an option then, maybe a hybrid implementation? I didn't get any warnings or issues using leafpic-revived to test this problem on android 12.

**Comment by wavexx** [comment]
I apologize for not answering sooner, I wasn't following notifications for this issue.

Indeed, if I wait about 3-4 seconds, the correct image is shown. Even though this seems a minor problem, it completely breaks the workflow of reviewing the last taken picture.

Seems like a big oversight in the mediastore api if that was the case? This doesn't seem to affect the built-in gallery app though, but I have no idea what it uses internally.

**Comment by leaumar** [comment]
It's like google just wants people to leave android... First the ugly mess that is android 12, then this mediastore stuff.

**Comment by wavexx** [comment]
@tibbi oh I understand, I didn't want to criticize simple-gallery or anything, just stated that yeah.. the resulting interaction is baffling.

I remember trying opencamera in combination with simple-gallery, and it looked to me that this didn't happen. Would it be helpful if I retested this combination?

Sadly, using opencamera (which I really love) on these phones just reveals how much trickery is done on the image acquisition side (pictures look like trash unless you have tons of light.. ) so it's not something I'm planning to go for as a  fix :/
