### ISSUE TITLE
Search photo by location 

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Gallery#2533]
Is it possible to search photos by location name? I mean the country from where the photo is. For e.g. Vienna

Thank  you

**Comment by tibbi** [comment]
we cannot add that, the app has no internet access

**Comment by kha84** [comment]
> we cannot add that, the app has no internet access

It's not "we cannot add that", it's more like "we don't want to request internet access privilege from users".

Have you considered other options? I'm guessing Android should be giving developers an option (an API) to map any given coordinates to a place, without requiring a direct privilege for accessing internet, if it's what you're trying to keep it

**Comment by tibbi** [comment]
not really, that cannot be done

**Comment by kha84** [comment]
Tell it to dozen of other  gallery apps who actually DO exactly that :)

But I kinda get your point - you're firmly standing on your position of not scaring users by asking some additional privileges for the app, by paying a price of self castrating it from bringing great features. Sure, I can get that.

Then here's an idea for you. You can emded some simple vector app into your app, it could be whole earth vector map, where each country will be represented by dozen or two of it's major cities. It won't bloat the app size much, prob by couple of Mb no more. But then you'll be able to show user photos on that vector map and even map GPS to some real cities. So instead of Vienna, you'll be showing "somewhere near to Vienna" but that would be something, at least.
