### ISSUE TITLE
Add to the description of the application on F-Droid a list of all file formats supported by the application

### ISSUE THREAD

**Issue by Korb** [SimpleMobileTools/Simple-Gallery#2646]
> All The Files You Need
> Simple Gallery supports a huge variety of different file types including JPEG, PNG, MP4, MKV, RAW, SVG, GIF, Panoramic photos, videos and many more, so you enjoy full flexibility in your choice of format. Ever wonder "Can I use this format on my Android"? Now the answer is yes.

https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/

From this description, I, choosing a gallery app, conclude that, for example, tiff and webp formats are not supported, and choose apps that explicitly state that they support these formats. Of course, I will not prepare a test set of files of many formats, and then install all the applications from the repository for testing. Also, it would be strange to get into the Issue Tracker of each application, and search to find mentions of all the formats I need to assume that these formats are supported by the application.

**Comment by tibbi** [comment]
I dont really want to list those, almost everything is supported. Webp included.

**Comment by OkyDooky** [comment]
Perhaps the list could at least be included in the About section of the app? Maybe in the Frequently Asked Questions option or its own section in the Other category? Probably the FAQ, since it could just be:
>**What formats can I view in this app?**
>This app supports viewing images, such as Jpeg, PNG, Gif, WebP(, and any others) and videos, such as MP4, WebM, (etc).

If you don't want to clutter the F-Droid (or PlayStore) description, this could be a way to provide a full list. Maybe the app description could remind users to check out the FAQs in the About section of the app before emailing or making an issue about something.
