### ISSUE TITLE
App crashes when open from camera app

### ISSUE THREAD

**Issue by germanfr** [SimpleMobileTools/Simple-Gallery#2722]
The gallery app crashes when I try to open it from the last picture shortcut of the camera app. The camera app crashes too. I use the Moto Camera app which came with my device.

![Screenshot_20230112-213002_1](https://user-images.githubusercontent.com/10391266/212175925-b10c8d28-748d-4ed5-a8cf-b01b42f03332.png)

Please tell me if you need more information.

**Comment by tibbi** [comment]
What makes you think that it is our gallery crashing? Some camera apps have a hardcoded gallery that is supposed to be used and if it is disabled, it just crashes.

**Comment by germanfr** [comment]
A dialog says gallery app crashed. It is not hardcoded, it asks and you can choose an app and select "always open with" if you want not to be asked. It used to work before (not always), but now it doesn't. I can't tell since when.

**Comment by tibbi** [comment]
try some other downloaded gallery, if it works

**Comment by germanfr** [comment]
Looks like the issue solved itself by removing the clear default preferences of the gallery app and selecting it again as default. Some cached identifier must have changed since I have the app I guess.
Sorry for the late reply. I don't know if this is a bug or not, so I leave you to close the issue if you think it's not. Thanks!

**Comment by germanfr** [comment]
I can comment here if this happens again in the future.

**Comment by mxdlx** [comment]
This happens to me, when I touch on the picture that was just taken then the screen goes black, I use the up from the bottom gesture (all screen motorola), the app preview is transparent and then I gesture up to close it. Sometimes touching the last picture on the camera a second time works. It seems the app gets unregistered from time to time as the gallery app. It should be something that the devs can solve as this behavior of being the default app does work for other features on Android.

**Comment by tibbi** [comment]
@mxdlx again, what makes you think that it is our app crashing? Some camera apps have a hardcoded gallery that is supposed to be used and if it is disabled, it just crashes.

**Comment by germanfr** [comment]
This is still happening to me as well. It's the simple gallery the one crashing, not the camera app. Maybe if I could extract somehow a trace from my phone it could help to clarify this?

**Comment by tibbi** [comment]
do you see any part of our app? Do other galleries work well?

**Comment by tibbi** [comment]
what camera app is it? Can it be found on Google Play?

**Comment by secretServant** [comment]
Firstly thanks for simple gallery, it's a great app!

I'd reopen the issue. The crash upon camera preview intent ONLY seems to occur with the simple gallery app. I use both [Aves Libre](https://f-droid.org/en/packages/deckers.thibault.aves.libre/) and [GCam Photos Preview](https://apt.izzysoft.de/fdroid/index/apk/com.google.android.apps.photos) to avoid crashes upon camera image preview.

Weirdly enough, other camera apps also don't cause simple gallery to crash, so it must be the way Motorola's camera app issues the intent. Other galleries seem to handle the intent properly though, so the crash should still be an open bug

Below are the error logs from logcat when the crash occurs. Please let me know if you need anymore details from me. This feature is pretty critical for anyone using the stock Motorola camera app alongside Simple Gallery Pro. 

Without a fix I really can't recommend this app in good conscious to other Motorola users.

`5-23 18:06:45.449 30167 30167 E AndroidRuntime: Process: com.simplemobiletools.gallery.pro, PID: 30167
05-23 18:06:45.449 30167 30167 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Parcel.createExceptionOrNull(Parcel.java:2380)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:2358)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2341)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2283)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.IActivityTaskManager$Stub$Proxy.activityPaused(IActivityTaskManager.java:4458)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.servertransaction.PauseActivityItem.postExecute(PauseActivityItem.java:64)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:250)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7877)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-23 18:06:45.449 30167 30167 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

`05-23 18:07:07.231 30490 30490 E AndroidRuntime: Process: com.simplemobiletools.gallery.pro, PID: 30490
05-23 18:07:07.231 30490 30490 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Parcel.createExceptionOrNull(Parcel.java:2380)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:2358)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2341)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2283)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.IActivityTaskManager$Stub$Proxy.activityPaused(IActivityTaskManager.java:4458)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.servertransaction.PauseActivityItem.postExecute(PauseActivityItem.java:64)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:250)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7877)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
05-23 18:07:07.231 30490 30490 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.view.SurfaceControl.access$300(SurfaceControl.java:82)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:2445)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at android.view.SurfaceControl$Transaction.reparent(SurfaceControl.java:2917)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at com.android.server.wm.SurfaceAnimator.transferAnimation(SurfaceAnimator.java:288)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:    at com.android.server.wm.WindowContainer.transferAnimation(WindowContainer.java:2149)
05-23 18:07:07.231 30490 30490 E AndroidRuntime:`
