### ISSUE TITLE
Hide delete checks

### ISSUE THREAD

**Issue by xDonatello** [SimpleMobileTools/Simple-Gallery#2937]
Suggestion for two new options in the settings.
The ability to hide these two checkboxes:
![Screenshot_2023-08-05-15-40-01-44_29b563cd0bc4fd07bd0c105b17b28204](https://github.com/SimpleMobileTools/Simple-Gallery/assets/13498803/8337e7d5-a0ea-43df-a1e1-abacda23ae2c)

**Comment by gmasil** [comment]
You mean you want to hide the checkboxes, you don't mean the existing settings:
File operations -> Always skip delete confirmation dialog
Recycle Bin -> Move items into the Recycle Bin instead of deleting

So it simply should look like this when you delete:
![gallery-hidden-delete-checkboxes](https://github.com/SimpleMobileTools/Simple-Gallery/assets/54176035/f7f631b6-3a0e-4481-9ff6-4a5b55d821e5)

**Comment by xDonatello** [comment]
> 

If I set "Always skip delete confirmation dialog", when I touch the trash can, the photo goes directly to the trash, it doesn't ask me to confirm the deletion 🤨

**Comment by xDonatello** [comment]
> You mean you want to hide the checkboxes, you don't mean the existing settings: File operations -> Always skip delete confirmation dialog Recycle Bin -> Move items into the Recycle Bin instead of deleting
> 
> So it simply should look like this when you delete: ![gallery-hidden-delete-checkboxes](https://user-images.githubusercontent.com/54176035/258743672-f7f631b6-3a0e-4481-9ff6-4a5b55d821e5.jpg)

If I set "Always skip delete confirmation dialog", when I touch the trash can, the photo goes directly to the trash, it doesn't ask me to confirm the deletion 🤨

**Comment by gmasil** [comment]
That is the intended behaviour: "don't ask me again, just delete"
And with the other setting you decide if it should go to recycle bin or beeing deleted permanentely.

**Comment by tibbi** [comment]
you cannot hide them, so just ignore them
