### ISSUE TITLE
Folder contents don't update

### ISSUE THREAD

**Issue by gappleto97** [SimpleMobileTools/Simple-Gallery#332]
A lot of pictures and video have been added that Gallery refuses to see, even if I force a refresh, even if I clear its cache.

Is there any sort of logging I can provide to help fix this?

**Comment by tibbi** [comment]
Hey, no logging, but some info could help. What is your Android version? Are those images/videos on an SD card? With what app have those media files been created? Are they visible in some other galleries? Thanks

**Comment by gappleto97** [comment]
They're in DCIM, internal. They don't show up in Telegram, which is the only other thing I have at the moment which looks for pictures.

What's going on is that I have a Tasker profile which moves pictures from the "freshly downloaded from drone" folder to DCIM so it gets backed up.

I don't think that should cause problems, but its the only thing I can think that's unusual here.

**Comment by tibbi** [comment]
Media files on Android are stored in a MediaStore, from where Im retrieving my data too. As Tasker handles probably all kinds of files, not just media, they might not be updating the MediaStore properly and my app is not aware of the files being there. You could maybe try including a folder manually in Settings, if they appear. Including has an issue tho which will be fixed in the next version released maybe today, so retry then.

**Comment by gappleto97** [comment]
Will do. Thanks.

**Comment by gappleto97** [comment]
It turns out Tasker has a command to scan for media. Once I knew what to look for it was easy to find it.

It *mostly* fixed the problem, along with your suggestion. I'm going to close this unless something else comes up.

Thank you.
