### ISSUE TITLE
Clicking to watch a video shouldn't prompt to choose the app to view the file

### ISSUE THREAD

**Issue by doronbehar** [SimpleMobileTools/Simple-Gallery#354]
When I click on a video in the gallery, I want the video to play instantly, regardless of the default preferred app I'm used to open this type of files.

IMO, it should be at a setting if not a default behavior.

What do you think?

**Comment by NitroNils** [comment]
It only prompts if I don't choose the 'use always option (not 'one time only')! So I don't see any problem.Sent from my Huawei Mobile-------- Original Message --------Subject: [SimpleMobileTools/Simple-Gallery] Clicking to watch a video shouldn't prompt to choose the app to view the file (#354)From: Doron Behar To: SimpleMobileTools/Simple-Gallery CC: Subscribed When I click on a video in the gallery, I want the video to play instantly, regardless of the default preferred app I'm used to open this type of files.
IMO, it should be at a setting if not a default behavior.
What do you think?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SimpleMobileTools/Simple-Gallery","title":"SimpleMobileTools/Simple-Gallery","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SimpleMobileTools/Simple-Gallery"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Clicking to watch a video shouldn't prompt to choose the app to view the file (#354)"}],"action":{"name":"View Issue","url":"https://github.com/SimpleMobileTools/Simple-Gallery/issues/354"}}}

**Comment by tibbi** [comment]
ye thats the exactly desired behaviour. If you always want to use a specific app, just select it. If for some reason you want to use a different video player for some apps, there is an "Open with" button at the fullscreen view, there you can select a different player.

**Comment by doronbehar** [comment]
I know that.

I don't want to choose 'Use always' because I don't want to always use this app to a open this type of videos. I want to use this app's player only to see videos from this app. And if I had opened a video file from the file explorer for example, I could want to `always use` a certain app to view it, like VLC for instance.

It just doesn't make sense IMO that within a certain app, I would be asked how do I want to complete a certain action and one of the options is using the app I'm using right now. It's the same thing with firefox for example: Even if firefox is not the default browser at the moment, pressing a link in firefox doesn't prompt me what browser I want to use in order to view the link. The reason is that since I'm currently use firefox it wouldn't have made any sense to use firefox to open links in other browser.

**Comment by tibbi** [comment]
I know what you mean, but this is the behaviour requested by most people, so Ill keep it like this. I dont want to add a toggle for it.

**Comment by ronandalton** [comment]
Hi, could you perhaps reconsider adding this as an option? Google Photos plays videos with its inbuilt video player when you tap to view them, so I don't think it's a bad idea to have the same behavior in this app. An option named "Always open videos in the internal video player" could be added which would cause the internal video player to open when a video is tapped in the gallery, instead of asking the Android system to play the video with its default player.

Thanks
