### ISSUE TITLE
Misplaced file is selected

### ISSUE THREAD

**Issue by yankee5** [SimpleMobileTools/Simple-Gallery#377]
Hold to select file and delete it.
After hold to select again, misplaced file is selected.
Moving to another folder will fix.

**Comment by tibbi** [comment]
Hey, are you using the latest version 2.14.4? It should be fixed there already

**Comment by yankee5** [comment]
I'm using v2.14.4.
Still reproduced.

**Comment by tibbi** [comment]
so it happens only in 1 folder? Do you have any other files except images/videos in that folder? Or do you have images/videos/gifs filtered out?

**Comment by yankee5** [comment]
I confirmed with 2 folders.

SD card/Pictures/Screenshots
It's contain .png file only.

SD card/DCIM/Camera
It's  contain .jpg, .png, .mp4 file.

Any other files isn't exist.
Checked by MiXplorer, "Show hidden file" is enabled.

File path includes "SD card", but my phone(Nextbit Robin) don't have SD card slot.
I guess it is Android's manners.

**Comment by tibbi** [comment]
Could you please test this version? To install the test version you first have to uninstall the current one, then allow installing apps from unknown sources in the security settings of your device. Please remove the ".zip" appendix after the file, its there just because github doesnt allow uploading .apk files. Then copy or send the .apk to your device through email or somehow. After running it the install will be straightforward. Thanks
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/1346740/app-release.apk.zip)

**Comment by yankee5** [comment]
After test, problem seems to solved.
Thanks for fix!

I found another problem in test, but not sure relation with this fix.
Should I open another issue?

Problem:
File select canceled by reflesh.

Steps to Reproduce:
1. Hold to select and delete file.
2. Hold to select file.
3. Reflesh icon show up when Hold to select other file. File select is canceled.

**Comment by tibbi** [comment]
Ive made it intentionally, to avoid wrong items being selected if the content changes
