### ISSUE TITLE
Pictures not saved if using camera button

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-Gallery#6]
If I open the camera app (in my case Open Camera) with the camera button and take a picture, after the picture was taken it returns to the gallery without saving the picture. I also checked on the file manager.

**Comment by tibbi** [comment]
I see, its because our implementation of that camera button is a bit different. While Open Camera returns back to the gallery after 1 photo, Simple Camera stays in the camera permanently (intentionally) and saves the photos correctly. I will test a couple more popular cameras/galleries and see if I can create something people are used to.
